#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings

title: ARBEITSVERSION - Data Science Crashkurs - Eine interaktive und praktische Einführung - Bitte lesen sie das Vorwort für weitere Informationen
author: Steffen Herbold
copyright: "2021"
logo: logo.png

repository:
  url: https://github.com/sherbold/einfuehrung-in-data-science
  path_to_book: content
  branch: main
  
  
html:
  use_repository_button: true
  
only_build_toc_files: true

execute:
  execute_notebooks: off